# See https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "clinvoice_adapter"
version = "0.11.0"
authors = ["Iron-E <code.iron.e@gmail.com>"]
description = "Shared adapter definitions for CLInvoice."

edition = "2021"
license = "GPL3"
readme = "README.md"
repository = "https://www.github.com/Iron-E/clinvoice_adapter"

[dependencies]
clinvoice_error = {branch = "release/0.3", git = "https://github.com/Iron-E/clinvoice_error"}
clinvoice_match = {branch = "release/0.4", git = "https://github.com/Iron-E/clinvoice_match"}
clinvoice_schema = {branch = "release/0.8", git = "https://github.com/Iron-E/clinvoice_schema"}

async-trait = "0.1"
futures = "0.3"
serde = {optional = true, version="1"}
sqlx = "0.5"

[dev-dependencies]
pretty_assertions = "1"
sqlx = {features = ["postgres", "runtime-tokio-rustls"], version = "0.5"}

[features]
default = ["sqlx_runtime_tokio_rustls"]
serde_support = ["serde/derive"]
sqlx_runtime_tokio_rustls = ["sqlx/runtime-tokio-rustls"]
